name       : woeusb
version    : 3.1.4
release    : 4
source     :
    - https://github.com/slacka/WoeUSB/archive/v3.1.4.tar.gz : 34b2ab1108c972f6d02fb09de3f6cf5c5cdeace519ad22bde6678062329a004e
license    : GPL-3.0
component  : system.utils
summary    : A tool to create a bootable Windows USB drive from an ISO
description: |
    WoeUSB is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. It is a fork of Congelli501's WinUSB.
builddeps  :
    - wxwidgets-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
