name       : woeusb
version    : 3.2.2
release    : 11
source     :
    - https://github.com/slacka/WoeUSB/archive/v3.2.2.tar.gz : 472746470e7874c81a72d5189f3d1fa9004ba1ea1d3c9715e78b64cbf8fc0948
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool to create a bootable Windows USB drive from an ISO
description: |
    WoeUSB is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. It is a fork of Congelli501's WinUSB.
builddeps  :
    - wxwidgets-devel
rundeps    :
    - parted
setup      : |
    # No words for this idiocy, script fails but at least
    # version is set correctly which is all we want
    ./setup-development-environment.bash || :

    %reconfigure
build      : |
    %make
install    : |
    %make_install
