name       : woeusb
version    : 2.2.2
release    : 1
source     :
    - https://github.com/slacka/WoeUSB/archive/v2.2.2.tar.gz : 430faf2ff552bd07d8abc4f2d3d42733968564f4149adf09555da15bfb1b2624
license    : GPL-3.0
component  : system.utils
summary    : A tool to create a bootable Windows USB drive from an ISO
description: |
    WoeUSB is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. It is a fork of Congelli501's WinUSB. 
builddeps  :
    - wxwidgets-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
